# Generated by Django 5.0.1 on 2024-01-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nAbonado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nAbonado', models.IntegerField()),
                ('nFactura', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('servicio', models.IntegerField()),
            ],
        ),
    ]
