# Generated by Django 5.0.1 on 2024-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0003_alter_facturas_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='servicio',
            field=models.CharField(max_length=50),
        ),
    ]
